apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-config
  namespace: pilot-load
data:
  # Each namespace has 1 25 replica service, 5 5 replica services, and 25 1 replica services. 75 pods each
  # Each service is exposed by a single Gateway, which has 200 instances
  # Overall this gives 64*75+200=5000 pods
  config.yaml: |
    nodeMetadata: {}
    istio:
      default: true # create all applicable istio resources for root namespace
    gracePeriod: 10s
    jitter:
      workloads: "1s"
      config: "15s"
    namespaces:
    - name: mesh
      istio:
        # create all applicable istio resources for each replica of 'mesh' namespace
        default: true
      replicas: 64
      applications:
      - name: big
        replicas: 1
        istio:
          # create all applicable istio resources for each replica of 'big' application
          default: true
          # create virtualService istio resource for each replica of 'big' application with referencing 'main' gateway
          virtualService:
            gateways: [main]
        instances: 25
      - name: medium
        replicas: 5
        istio:
          # create all applicable istio resources for each replica of 'medium' application
          default: true
          # create virtualService istio resource for each replica of 'medium' application with referencing 'main' gateway
          virtualService:
            gateways: [main]
        instances: 5
      - name: small
        replicas: 25
        istio:
          # create all applicable istio resources for each replica of 'small' application
          default: true
          # create virtualService istio resource for each replica of 'small' application with referencing 'main' gateway
          virtualService:
            gateways: [main]
        instances: 1
    - name: gateway
      replicas: 1
      applications:
      - name: ingress
        replicas: 1
        istio:
          # create all applicable istio resources for each replica of 'gateway' application
          default: true
        instances: 20
        appType: router
        gateways: # create istio gateway for 'ingress' application
          name: main
          enabled: true