apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-config
  namespace: pilot-load
data:
  # Each namespace has 10x100 and 1x1000
  config.yaml: |
    nodeMetadata: {}
    jitter:
      workloads: "1s"
      config: "0"
    namespaces:
    - name: mesh
      replicas: 1
      istio:
          default: true
      applications:
      - name: big
        replicas: 10
        istio:
          default: true
        instances: 100
      - name: huge
        istio:
          default: true
        replicas: 1
        instances: 1000
