apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-config
  namespace: pilot-load
data:
  # Each namespace has 1 25 replica service, 5 5 replica services, and 25 1 replica services. 75 pods each
  # Each service is exposed by a single Gateway, which has 200 instances.
  # Pods have no sidecars
  # Overall this gives 64*75+200=5000 pods
  config.yaml: |
    nodeMetadata: {}
    jitter:
      workloads: "1s"
      config: "15s"
    namespaces:
    - name: mesh
      replicas: 64
      applications:
      - name: big
        replicas: 1
        instances: 25
        appType: external
        istio:
          virtualService:
            gateways: [gateway/main]
      - name: medium
        replicas: 5
        instances: 5
        appType: external
        istio:
          virtualService:
            gateways: [gateway/main]
      - name: small
        replicas: 25
        instances: 1
        appType: external
        istio:
          virtualService:
            gateways: [gateway/main]
    - name: gateway
      replicas: 1
      applications:
      - name: ingress
        replicas: 1
        instances: 200
        appType: router
        gateways:
          name: main
          enabled: true